Feat/design_game: add the design game
Kiclos/filles-du-numerique pull request #9
Opened 2023-02-07 15:59 UTC by Kalo0m

### Design game

![image](https://user-images.githubusercontent.com/61421713/217294302-ec72eea5-fd30-46bb-b315-a1975ed6e8d1.png)

we can drag elements form the bottomsheet and change the background color

![image](https://user-images.githubusercontent.com/61421713/217294433-68f7b76c-8e97-465f-8009-9d6203c3cf24.png)

and when the user finish he can click the "next" button to have more informations about the job

![image](https://user-images.githubusercontent.com/61421713/217296288-018292f1-e95b-431e-892c-3b60cfcaf806.png)

2023-02-07 16:36 UTC, Rakwa requested changes
Améliorations sur le css : 
- Bouton terminer a mettre au centre
- Déplacer le select de la couleur juste à droite du texte
- Centrer le texte dans le bouton connexion

2023-02-07 16:36 UTC, Rakwa commented on src/components/Games/MaintenanceGame.vue
> +  components: { PauseMenu, Meteorite, Messages, Choix },
Ne pas push ce fichier

2023-02-07 16:36 UTC, Rakwa commented on src/assets/scss/main.scss
> +}
Il faut vraiment ca ? Risque d'impact pour les autres jeux ?

2023-02-07 16:42 UTC, Kalo0m commented on src/assets/scss/main.scss
> +}
nan tkt

2023-02-08 10:32 UTC, Rakwa commented
@Kalo0m Merge en 4eme

2023-02-09 12:36 UTC, merged